"""s5 evolution jobs and reports

Revision ID: 01caa43c3bc5
Revises: dcd9887cee3b
Create Date: 2026-07-05 15:50:47.119744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01caa43c3bc5'
down_revision: Union[str, None] = 'dcd9887cee3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evolution_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('evaluate', 'promote_rescore', 'rollback_rescore', name='evolution_job_kind', native_enum=False, length=24), nullable=False),
    sa.Column('param_set_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('queued', 'running', 'done', 'failed', name='evolution_job_state', native_enum=False, length=24), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('detail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['param_set_id'], ['param_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('param_sets', sa.Column('report_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('param_sets', 'report_json')
    op.drop_table('evolution_jobs')
    # ### end Alembic commands ###
